### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by shuuichikun** [jwvhewitt/gearhead-2#16]
I get an error with compiling on line 75,1 of ghsensor.pp. 

ghsensor.pp(75,1) Warning: Unknown procedure directive had to be ignored: "POWERSOURCE"
ghsensor.pp(75,1) Fatal: Syntax error, "IMPLEMENTATION" expected but "identifier POWERSOURCE" found
Fatal: Compilation aborted
Error: <FPC> returned an error exitcode.

It seems that the word is loose on line 75 with no supporting commands.

**Comment by jwvhewitt** [comment]
Weird. It has been fixed. Thanks for letting me know about it.
